"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, GripVertical, X } from "lucide-react";
import type { ProductRecord } from "@/lib/content";
import type { ProductCategoryV1 } from "@/lib/site-content-config-v1";
import { AdminHeader, Stat, Status } from "@/components/admin/admin-ui";

type Locale = "zh" | "en" | "ar";

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="admin-modal-backdrop" onMouseDown={onClose}>
    <section aria-labelledby={`modal-${title}`} aria-modal="true" className="admin-modal" onMouseDown={(event)=>event.stopPropagation()} role="dialog">
      <header><h2 id={`modal-${title}`}>{title}</h2><button aria-label="关闭" onClick={onClose} type="button"><X /></button></header>
      {children}
    </section>
  </div>;
}

function LocaleTabs({ value, onChange }: { value: Locale; onChange: (locale: Locale) => void }) {
  return <div className="locale-tabs" role="tablist">
    {([['zh','中文'],['en','English'],['ar','العربية']] as const).map(([locale,label])=><button aria-selected={locale===value} className={locale===value?'active':''} key={locale} onClick={()=>onChange(locale)} role="tab" type="button">{label}</button>)}
  </div>;
}

function MoveButtons({ label, index, count, onMove }: { label: string; index: number; count: number; onMove: (delta: number) => void }) {
  return <span className="sort-actions"><GripVertical aria-hidden="true"/><button aria-label={`上移 ${label}`} disabled={index===0} onClick={()=>onMove(-1)} type="button"><ArrowUp/></button><button aria-label={`下移 ${label}`} disabled={index===count-1} onClick={()=>onMove(1)} type="button"><ArrowDown/></button></span>;
}

function move<T>(items: T[], index: number, delta: number) { const next=[...items]; const target=index+delta; if(target<0||target>=items.length)return next; [next[index],next[target]]=[next[target],next[index]]; return next; }

export function PagesWorkspace() {
  const [locale,setLocale]=useState<Locale>('zh');
  const [sections,setSections]=useState(["企业介绍","产品介绍","合作优势","联系方式","合作咨询"]);
  return <><AdminHeader eyebrow="CONTENT" title="页面内容" description="维护三语文案、板块顺序、版式、草稿与发布版本。" actions={<Link className="admin-secondary" href={`/${locale}?preview=draft`} target="_blank">预览草稿</Link>}/><LocaleTabs value={locale} onChange={setLocale}/><section className="admin-card"><div className="admin-card-title"><div><h2>官网首页 · home</h2><Status>草稿</Status></div><span>当前版本 V1</span></div><div className="admin-form"><label>预设版式<select defaultValue="sculptural"><option value="sculptural">柔和雕塑工艺</option><option value="editorial">编辑式图文</option><option value="compact">紧凑展示</option></select></label><label>显示顺序<input defaultValue="0" type="number"/></label><label className="admin-switch"><input defaultChecked type="checkbox"/> 启用板块</label><div className="section-order"><b>板块编排</b>{sections.map((item,index)=><div data-testid="page-section" draggable key={item} onDragOver={(event)=>event.preventDefault()} onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(index))} onDrop={(event)=>{const from=Number(event.dataTransfer.getData('text/plain')); const copy=[...sections]; const [picked]=copy.splice(from,1); copy.splice(index,0,picked); setSections(copy);}}><MoveButtons count={sections.length} index={index} label={item} onMove={(delta)=>setSections(move(sections,index,delta))}/><strong>{index+1}. {item}</strong><select defaultValue="default"><option value="default">默认版式</option><option value="reverse">图文反转</option></select></div>)}</div><button className="admin-primary" type="button">保存草稿</button></div></section></>;
}

export function ProductsWorkspace({ categories, products }: { categories: ProductCategoryV1[]; products: ProductRecord[] }) {
  const [query,setQuery]=useState(''); const [category,setCategory]=useState('all'); const [status,setStatus]=useState('all'); const [modal,setModal]=useState<{type:'new'|'edit'|'history'; product?:ProductRecord}|null>(null);
  const orderedCategories=useMemo(()=>categories.toSorted((left,right)=>left.sortOrder-right.sortOrder||left.slug.localeCompare(right.slug)),[categories]);
  const categoryById=useMemo(()=>new Map(orderedCategories.map(item=>[item.id,item])),[orderedCategories]);
  const rows=useMemo(()=>products.filter(p=>{const code=p.specifications[0]?.value.zh||''; return (!query||`${p.translations.zh.name} ${code}`.toLowerCase().includes(query.toLowerCase()))&&(category==='all'||p.categoryId===category)&&(status==='all'||p.status===status)}),[products,query,category,status]);
  return <><AdminHeader eyebrow="CATALOG" title="产品目录" description="管理动态分类下的三语介绍、多图与可排序规格。" actions={<button className="admin-primary" onClick={()=>setModal({type:'new'})}>新建产品</button>}/><div className="admin-stats">{orderedCategories.slice(0,2).map(item=><Stat key={item.id} label={item.translations.zh.name} value={products.filter(product=>product.categoryId===item.id).length}/>) }<Stat label="待补翻译" value="0"/><Stat label="产品图片" value={products.reduce((sum, product) => sum + product.images.length, 0)}/></div><div className="admin-toolbar"><input onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或产品编号" value={query}/><select aria-label="类目筛选" onChange={e=>setCategory(e.target.value)} value={category}><option value="all">全部类目</option>{orderedCategories.map(item=><option key={item.id} value={item.id}>{item.translations.zh.name}{item.enabled?'':'（已停用）'}</option>)}</select><select aria-label="状态筛选" onChange={e=>setStatus(e.target.value)} value={status}><option value="all">全部状态</option><option value="published">已发布</option><option value="draft">草稿</option></select></div><div className="admin-table product-table"><div className="table-row table-head"><span>产品</span><span>类目</span><span>规格</span><span>状态</span><span>操作</span></div>{rows.map(item=>{const code=item.specifications[0]?.value.zh||item.id; const itemCategory=categoryById.get(item.categoryId); const image=item.images[0]; return <div className="table-row" data-testid="product-row" key={item.id}><span className="product-cell">{image?<Image alt={item.translations.zh.name} height={52} src={image.url} width={52}/>:null}<b>{item.translations.zh.name}<small>{code}</small></b></span><span>{itemCategory?.translations.zh.name??item.categorySlug}{itemCategory&&!itemCategory.enabled?'（已停用）':''}</span><span>{item.specifications.length} 项</span><span><Status tone={item.status}>{item.status === "published" ? "已发布" : "草稿"}</Status></span><span><button aria-label={`编辑 ${code}`} onClick={()=>setModal({type:'edit',product:item})}>编辑</button><button aria-label={`历史版本 ${code}`} onClick={()=>setModal({type:'history',product:item})}>历史版本</button></span></div>})}{rows.length===0?<p className="admin-empty">没有符合条件的产品</p>:null}</div>{modal?<Modal onClose={()=>setModal(null)} title={modal.type==='new'?'新建产品':modal.type==='edit'?'编辑产品':'历史版本'}>{modal.type==='history'?<div className="version-list"><p>V1 · 已发布 · 当前版本</p></div>:<form className="admin-form" onSubmit={(e)=>{e.preventDefault();setModal(null)}}><label>产品名称<input defaultValue={modal.product?.translations.zh.name}/></label><label>产品编号<input defaultValue={modal.product?.specifications[0]?.value.zh}/></label><label>类目<select defaultValue={modal.product?.categoryId??orderedCategories.find(item=>item.enabled)?.id}>{orderedCategories.map(item=><option disabled={!item.enabled} key={item.id} value={item.id}>{item.translations.zh.name}{item.enabled?'':'（已停用）'}</option>)}</select></label><button className="admin-primary">保存草稿</button></form>}</Modal>:null}</>;
}

const initialDimensions=["产品类型","外形轮廓","尺寸规格","厚度结构","表面面料","颜色","包装与标识","其他需求"];
export function CustomizationWorkspace(){const [locale,setLocale]=useState<Locale>('zh'); const [items,setItems]=useState(initialDimensions); const [modal,setModal]=useState<'add'|'edit'|null>(null); return <><AdminHeader eyebrow="CUSTOM DEVELOPMENT" title="定制开发" description="维护前台可见的定制维度、选项与开发流程。" actions={<button className="admin-primary" onClick={()=>setModal('add')}>新增维度</button>}/><LocaleTabs value={locale} onChange={setLocale}/><section className="admin-card"><div className="admin-card-title"><div><h2>定制维度</h2><Status tone="published">已启用</Status></div><span>拖拽或使用箭头调整顺序</span></div><div className="dimension-list">{items.map((item,index)=><div draggable key={item} onDragOver={(event)=>event.preventDefault()} onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(index))} onDrop={(event)=>{const from=Number(event.dataTransfer.getData('text/plain')); const copy=[...items]; const [picked]=copy.splice(from,1);copy.splice(index,0,picked);setItems(copy)}}><MoveButtons count={items.length} index={index} label={item} onMove={(delta)=>setItems(move(items,index,delta))}/><strong>{item}</strong><input defaultValue={index%2?'按样确认、支持多规格':'可选标准方案或来样开发'}/><button aria-label={`编辑选项 ${item}`} onClick={()=>setModal('edit')}>编辑选项</button><label><input defaultChecked type="checkbox"/> 启用</label></div>)}</div><button className="admin-primary">保存草稿</button></section>{modal?<Modal onClose={()=>setModal(null)} title={modal==='add'?'新增维度':'编辑选项'}><form className="admin-form" onSubmit={e=>{e.preventDefault(); if(modal==='add')setItems([...items,'新定制维度']); setModal(null)}}><label>{modal==='add'?'维度名称':'选项（每行一个）'}{modal==='add'?<input required/>:<textarea defaultValue={'标准方案\n来样开发'}/>}</label><button className="admin-primary">保存</button></form></Modal>:null}</>}

export function UsersWorkspace(){const [modal,setModal]=useState<'invite'|'group'|null>(null); const resources=["页面内容","产品目录","媒体","合作意向","用户","权限组","系统设置","审计日志"]; return <><AdminHeader eyebrow="ACCESS CONTROL" title="用户与权限" description="自定义权限组；服务端校验与 RLS 同时生效，系统所有者受保护。" actions={<button className="admin-primary" onClick={()=>setModal('invite')}>邀请管理员</button>}/><section className="admin-card"><div className="admin-card-title"><div><h2>管理员</h2><Status tone="published">1 位系统所有者</Status></div></div><p>系统所有者 · 全部权限 · 不可删除或停用</p></section><section className="admin-card"><div className="admin-card-title"><div><h2>权限矩阵 · 内容管理员</h2><Status>草稿</Status></div><button className="admin-secondary" onClick={()=>setModal('group')}>新建权限组</button></div><div className="permission-matrix">{resources.map(resource=><label className="matrix-resource" key={resource}><strong>{resource}</strong><input defaultChecked type="checkbox"/> 查看</label>)}</div><button className="admin-primary">保存权限变更</button></section>{modal?<Modal onClose={()=>setModal(null)} title={modal==='invite'?'邀请管理员':'新建权限组'}><form className="admin-form" onSubmit={e=>{e.preventDefault();setModal(null)}}><label>{modal==='invite'?'管理员邮箱':'权限组名称'}<input required type={modal==='invite'?'email':'text'}/></label><button className="admin-primary">{modal==='invite'?'发送邀请':'创建权限组'}</button></form></Modal>:null}</>}

const auditEvents=[['发布','页面内容','官网首页 V3'],['回滚','产品目录','BP-004 → V2'],['导出','合作意向','筛选结果 24 条'],['权限变更','权限组','销售跟进']];
export function AuditWorkspace(){const [query,setQuery]=useState(''); const [action,setAction]=useState('all'); const rows=auditEvents.filter(row=>(action==='all'||row[0]===action)&&(!query||row.join(' ').includes(query))); return <><AdminHeader eyebrow="TRACEABILITY" title="审计日志" description="发布、回滚、删除、导出、权限变更与线索跟进均保留记录。"/><div className="admin-toolbar"><input onChange={e=>setQuery(e.target.value)} placeholder="搜索资源或操作人" value={query}/><select aria-label="操作筛选" onChange={e=>setAction(e.target.value)} value={action}><option value="all">全部操作</option><option value="发布">发布</option><option value="回滚">回滚</option><option value="导出">导出</option><option value="权限变更">权限变更</option></select></div><div className="admin-table"><div className="table-row table-head"><span>时间</span><span>操作</span><span>资源</span><span>详情</span><span>结果</span></div>{rows.map((row,index)=><div className="table-row" data-testid="audit-row" key={index}><span>预览记录</span><span>{row[0]}</span><span>{row[1]}</span><span>{row[2]}</span><span><Status tone="published">成功</Status></span></div>)}</div></>}
