import { updateInquiry } from "@/app/admin/actions";
import { ActionForm } from "@/components/admin/action-form";
import { AdminHeader, Stat, Status } from "@/components/admin/admin-ui";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import Link from "next/link";

export default async function InquiriesAdmin(){
  const supabase=await createSupabaseServerClient(); const {data}=supabase?await supabase.from("inquiries").select("id,name,company,country_code,email,product_category,estimated_quantity,message,status,created_at").is("deleted_at",null).order("created_at",{ascending:false}).limit(30):{data:null};
  const rows=data??[{id:"preview-inquiry",name:"示例客户",company:"Sample Brand",country_code:"AE",email:"buyer@example.com",product_category:"cups",estimated_quantity:"5,000 pcs",message:"需要确认柔软罩杯的打样周期与可选颜色。",status:"new",created_at:new Date().toISOString()}];
  return <><AdminHeader eyebrow="LEADS" title="合作意向" description="搜索、筛选、分配并记录每次客户跟进；线索不会自动清理。" actions={<Link className="admin-secondary" href="/api/admin/inquiries/export">导出 CSV</Link>}/><div className="admin-stats"><Stat label="全部线索" value={rows.length}/><Stat label="新线索" value={rows.filter(x=>x.status==="new").length}/><Stat label="跟进中" value={rows.filter(x=>x.status==="in_progress").length}/><Stat label="待发送邮件" value="—"/></div><div className="admin-toolbar"><input placeholder="搜索姓名、公司、邮箱"/><select><option>全部状态</option><option>新线索</option><option>跟进中</option><option>已成交</option></select><select><option>全部国家/地区</option></select></div>{rows.map((row)=><section className="admin-card inquiry-card" key={row.id}><div className="admin-card-title"><div><h2>{row.name} · {row.company}</h2><Status tone={row.status}>{({new:"新线索",in_progress:"跟进中",won:"已成交",closed:"已关闭",spam:"垃圾信息"} as Record<string,string>)[row.status]}</Status></div><time>{new Date(row.created_at).toLocaleString("zh-CN")}</time></div><div className="inquiry-summary"><p><b>{row.country_code}</b> · {row.email}</p><p>{row.product_category} · {row.estimated_quantity}</p><blockquote>{row.message}</blockquote></div><ActionForm action={updateInquiry} className="admin-form inline-followup"><input name="id" type="hidden" value={row.id}/><label>状态<select defaultValue={row.status} name="status"><option value="new">新线索</option><option value="in_progress">跟进中</option><option value="won">已成交</option><option value="closed">已关闭</option><option value="spam">垃圾信息</option></select></label><label>内部跟进备注<textarea name="note" placeholder="记录电话、邮件或下一步计划" rows={3}/></label></ActionForm></section>)}</>;
}
